### ISSUE TITLE
there is some spelling mistake

### ISSUE THREAD

**Issue by yangman-c** [happypeter/gitbeijing#11]
hello peter, in article there has some spelling mistake， i will look up again, and paste the wrong place in here.
英文不好哦 
您好 peter 在文章里， 有一些汉字的拼写错误呢。我改天在看一遍， 把错误的地方给你贴出来，方便你查找

**Comment by happypeter** [comment]
谢谢，我也正在校正。目前 第一天到第三天 的内容已经我自己已经校正完毕。所以如果你要帮我就在我的基础上再校正一下，找找语句不通顺的地方。

后面的内容我还会有比较大的变动，所以不要浪费你的时间
