### ISSUE TITLE
准备制作电子书

### ISSUE THREAD

**Issue by happypeter** [happypeter/gitbeijing#16]
现在正在审阅书稿。

**Comment by happypeter** [comment]
第十章 更多 Github 技巧 done

**Comment by happypeter** [comment]
现在可以制作电子书了。

**Comment by billie66** [comment]
仍然借助 gitbook 吗

**Comment by happypeter** [comment]
他们 pdf 太难看了，可以考虑用自己的 pdf 生成器，而其他格式用它的

**Comment by billie66** [comment]
关于 latex 的文档，结构挺清晰的

https://www.sharelatex.com/learn

**Comment by happypeter** [comment]
selfstore 上的介绍：

本书中 Peter 邀你一起走进 Github 的世界。避开命令行，通过图形化客户端和网站交互来实现版本控制操作。Git 版本控制学起来挺复杂，这里展示的是一套最容易上手的操作方式，但是同时也足够强大，可以照顾到所有的日常使用情形。

**Comment by billie66** [comment]
这本书已经发布了  https://selfstore.io/products/341
