### ISSUE TITLE
gitbeijing访问有问题啊

### ISSUE THREAD

**Issue by pod4g** [happypeter/gitbeijing#24]
![gitbeijing访问有问题啊](http://7xt9n8.com2.z0.glb.clouddn.com/86EC931C-4D95-408A-9DDD-36B38FAD0AC9.png)

**Comment by happypeter** [comment]
http://book.haoduoshipin.com/gitbeijing/ 用这个吧

未来本书应该会托管在

haoqicat.com/gitbeijing

或者是 peterandbillie.com/gitbeijing


Gitbeijing.com 这个域名应该不会用了，备案太麻烦了。

**Comment by pod4g** [comment]
谢谢

**Comment by happypeter** [comment]
托管到了 github pages 所有 gitbeijing.com 域名现在是可以用的。
