### ISSUE TITLE
algolia 搜索 

### ISSUE THREAD

**Issue by happypeter** [happypeter/gitbeijing#30]
```html

<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 
<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
 apiKey: 'e7d7fcfb5ab7b179b4e5424f16404c6a', 
 indexName: 'gitbeijing', 
 inputSelector: '### REPLACE ME ####', 
 debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 
```
- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field. 
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/) 
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/gitbeijing.json). Feel free to open pull requests!

**Comment by happypeter** [comment]
上面是 algolia 官方给我的回复，所以可以开始把代码集成到项目中了。

#31 完成之后再做本项目。

**Comment by billie66** [comment]
好的

**Comment by billie66** [comment]
algolia 搜索到的结果网址是 gitbeijing.com/issues.html#header

但是实际的网址是 gitbeijing.com/issues 所以会出现 404 错误

**Comment by billie66** [comment]
```
const slug = node.fields.slug
createPage({
  path: `${slug.slice(0, slug.length - 1)}.html`,
  component: path.resolve(`./src/templates/blog-post.js`),
  context: {
    slug: slug
  }
})
```

生成页面的时候，设置一下 path 属性，就可以在页面路径中添加 .html 后缀

**Comment by billie66** [comment]
algolia 已经收集了 gitbeijing 的老内容，所以有些搜索匹配项的页面找不到

**Comment by happypeter** [comment]
24 小时爬一次。

**Comment by billie66** [comment]
调整了一下样式，algolia 搜索集成完成
