### ISSUE TITLE
翻译 github flow

### ISSUE THREAD

**Issue by happypeter** [happypeter/gitbeijing#9]
https://guides.github.com/introduction/flow/index.html

代码直接用人家的，英文变中文后放到 billie66/github-flow 仓库的 gh-pages 分支

回头我用 flow.gitbeijing.com 指过去

**Comment by billie66** [comment]
代码已经跑起来

http://billie66.github.io/github-flow/

**Comment by happypeter** [comment]
cool

**Comment by billie66** [comment]
文章已经翻译完了

**Comment by happypeter** [comment]
cool 回头我校正一下放到 gitbeijing 主 repo 中
